### PR TITLE
Fixed "Undefined" IP addr in the UI for containers

### PR DESCRIPTION
**Pull request by H2so4**

### CODE REVIEW

**Comment by googley** [comment]
What is the version of lxc-info ? Does it works with lxc-info 0.8 ?

**Comment by H2so4** [comment]
No it doesn't.  However, it should be fair to require a version of at least 0.9 as there have been a TON of feature and security updates since then, including nested containers.

**Comment by H2so4** [comment]
@googley is this not getting merged because LXC version 0.8 is a hard requirement?

**Comment by naisanza** [comment]
@H2so4 This works perfectly for me! [Image](http://i.imgur.com/FkTqFDS.png)

**Comment by ElieDeloumeau** [comment]
@H2so4 yes and in the next version, i'll use the lxc python api.

**Comment by ElieDeloumeau** [comment]
Fixed in https://github.com/lxc-webpanel/lxc-rest

**Comment by ElieDeloumeau** [comment]
No, we're doing a major refactoring : https://github.com/lxc-webpanel/LXC-Web-Panel/tree/develop

**Pull request closed without merging**
